# Generated by Django 4.1.7 on 2023-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pgx", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="node_id",
        ),
        migrations.RemoveField(
            model_name="dataaccesshistory",
            name="data_request",
        ),
        migrations.RemoveField(
            model_name="datarequester",
            name="user",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="node_id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="gender",
        ),
        migrations.DeleteModel(
            name="DataRequest",
        ),
    ]
